import React from 'react';
import { LegalLayout } from '../components/LegalLayout';

const sections = [
  { id: 'overview', title: 'Overview', level: 1 },
  { id: 'information-we-collect', title: 'Information We Collect', level: 1 },
  { id: 'personal-information', title: 'Personal Information', level: 2 },
  { id: 'meeting-data', title: 'Meeting Data and Transcripts', level: 2 },
  { id: 'technical-information', title: 'Technical Information', level: 2 },
  { id: 'how-we-use-information', title: 'How We Use Information', level: 1 },
  { id: 'service-provision', title: 'Service Provision', level: 2 },
  { id: 'communication', title: 'Communication', level: 2 },
  { id: 'improvement', title: 'Improvement and Analytics', level: 2 },
  { id: 'information-sharing', title: 'Information Sharing', level: 1 },
  { id: 'third-party-integrations', title: 'Third-Party Integrations', level: 2 },
  { id: 'legal-requirements', title: 'Legal Requirements', level: 2 },
  { id: 'data-security', title: 'Data Security', level: 1 },
  { id: 'encryption', title: 'Encryption Standards', level: 2 },
  { id: 'access-controls', title: 'Access Controls', level: 2 },
  { id: 'data-retention', title: 'Data Retention', level: 2 },
  { id: 'your-rights', title: 'Your Rights', level: 1 },
  { id: 'access-portability', title: 'Access and Portability', level: 2 },
  { id: 'correction-deletion', title: 'Correction and Deletion', level: 2 },
  { id: 'opt-out', title: 'Opt-Out Preferences', level: 2 },
  { id: 'international-users', title: 'International Users', level: 1 },
  { id: 'kazakhstan-law', title: 'Kazakhstan Law Compliance', level: 2 },
  { id: 'gdpr-considerations', title: 'GDPR Considerations', level: 2 },
  { id: 'data-transfers', title: 'International Data Transfers', level: 2 },
  { id: 'children-privacy', title: 'Children\'s Privacy', level: 1 },
  { id: 'changes-to-policy', title: 'Changes to This Policy', level: 1 },
  { id: 'contact-us', title: 'Contact Us', level: 1 }
];

export const PrivacyPolicyPage: React.FC = () => {
  return (
    <LegalLayout
      title="Privacy Policy"
      lastUpdated="January 15, 2025"
      sections={sections}
    >
      {/* Content */}
      <div className="legal-content">
        <section id="overview">
          <h2>1. Overview</h2>
          <p>
            Welcome to RavenAI ("we," "our," or "us"). This Privacy Policy explains how we collect, use, 
            disclose, and safeguard your information when you use our meeting intelligence platform and related services 
            (collectively, the "Service"). 
          </p>
          <p>
            Raven AI is committed to protecting your privacy and ensuring transparency about our data practices. 
            This policy applies to all users of our platform, including visitors to our website, registered users, 
            and participants in recorded meetings.
          </p>
          <p>
            By using our Service, you agree to the collection and use of information in accordance with this policy. 
            If you disagree with any part of this policy, please do not use our Service.
          </p>
        </section>

        <section id="information-we-collect">
          <h2>2. Information We Collect</h2>
          
          <div id="personal-information">
            <h3>2.1 Personal Information</h3>
            <p>We collect personal information that you provide directly to us, including:</p>
            <ul>
              <li><strong>Account Information:</strong> Name, email address, profile picture, and authentication credentials</li>
              <li><strong>Contact Information:</strong> Phone number, company name, job title (if provided)</li>
              <li><strong>Profile Data:</strong> User preferences, settings, and customization choices</li>
              <li><strong>Communication Data:</strong> Messages sent through our platform, support requests, and feedback</li>
            </ul>
          </div>

          <div id="meeting-data">
            <h3>2.2 Meeting Data and Transcripts</h3>
            <p>When you use our meeting intelligence features, we collect:</p>
            <ul>
              <li><strong>Audio Recordings:</strong> Audio content from meetings (when explicitly authorized)</li>
              <li><strong>Transcriptions:</strong> Text transcripts generated from audio recordings</li>
              <li><strong>Meeting Metadata:</strong> Meeting titles, dates, duration, participant information</li>
              <li><strong>AI-Generated Content:</strong> Summaries, action items, key points, and insights generated by our AI</li>
              <li><strong>User Notes:</strong> Manual notes, annotations, and comments added by users</li>
              <li><strong>Integration Data:</strong> Information from connected platforms (Google Calendar, Slack, etc.)</li>
            </ul>
            <p>
              <strong>Important:</strong> We only record and process meetings with explicit consent from the meeting organizer. 
              All participants are notified when recording is active.
            </p>
          </div>

          <div id="technical-information">
            <h3>2.3 Technical Information</h3>
            <p>We automatically collect certain technical information, including:</p>
            <ul>
              <li><strong>Device Information:</strong> Browser type, operating system, device identifiers</li>
              <li><strong>Usage Analytics:</strong> Feature usage patterns, session duration, click-through rates</li>
              <li><strong>Performance Data:</strong> Error logs, response times, system performance metrics</li>
              <li><strong>Network Information:</strong> IP address, location data (general geographic area)</li>
              <li><strong>Cookies and Tracking:</strong> Session tokens, preference cookies, analytics cookies</li>
            </ul>
          </div>
        </section>

        <section id="how-we-use-information">
          <h2>3. How We Use Information</h2>
          
          <div id="service-provision">
            <h3>3.1 Service Provision</h3>
            <ul>
              <li>Process and transcribe meeting audio recordings</li>
              <li>Generate AI-powered summaries and insights</li>
              <li>Provide search and organization features for meeting data</li>
              <li>Enable integrations with third-party platforms</li>
              <li>Maintain user accounts and authentication</li>
            </ul>
          </div>

          <div id="communication">
            <h3>3.2 Communication</h3>
            <ul>
              <li>Send service-related notifications and updates</li>
              <li>Respond to user inquiries and provide customer support</li>
              <li>Share important changes to our terms or services</li>
              <li>Send marketing communications (with your consent)</li>
            </ul>
          </div>

          <div id="improvement">
            <h3>3.3 Improvement and Analytics</h3>
            <ul>
              <li>Analyze usage patterns to improve our AI models</li>
              <li>Enhance platform performance and user experience</li>
              <li>Develop new features and capabilities</li>
              <li>Conduct research and analytics (using aggregated, anonymized data)</li>
            </ul>
          </div>
        </section>

        <section id="information-sharing">
          <h2>4. Information Sharing</h2>
          <p>We do not sell your personal information. We may share your information in the following limited circumstances:</p>
          
          <div id="third-party-integrations">
            <h3 style={{ color: 'var(--dashboard-black, #000000)' }}>4.1 Third-Party Integrations</h3>
            <ul>
              <li><strong>Google Services:</strong> Calendar data and OAuth authentication</li>
              <li><strong>Slack Integration:</strong> Workspace and channel information (with your authorization)</li>
              <li><strong>Cloud Storage:</strong> Secure data storage with enterprise-grade providers</li>
              <li><strong>Analytics Providers:</strong> Aggregated, anonymized usage statistics</li>
            </ul>
          </div>

          <div id="legal-requirements">
            <h3 style={{ color: 'var(--dashboard-black, #000000)' }}>4.2 Legal Requirements</h3>
            <p>We may disclose your information if required by law or in good faith belief that such action is necessary to:</p>
            <ul>
              <li>Comply with legal process or government requests</li>
              <li>Protect and defend our rights and property</li>
              <li>Investigate potential violations of our terms of service</li>
              <li>Protect the safety and security of users and the public</li>
            </ul>
          </div>
        </section>

        <section id="data-security">
          <h2 style={{ color: 'var(--dashboard-black, #000000)' }}>5. Data Security</h2>
          
          <div id="encryption">
            <h3 style={{ color: 'var(--dashboard-black, #000000)' }}>5.1 Encryption Standards</h3>
            <ul>
              <li><strong>In Transit:</strong> All data transmitted using TLS 1.3 encryption</li>
              <li><strong>At Rest:</strong> AES-256 encryption for stored data</li>
              <li><strong>Database Security:</strong> Encrypted database connections and storage</li>
              <li><strong>API Security:</strong> OAuth 2.0 and secure API authentication</li>
            </ul>
          </div>

          <div id="access-controls">
            <h3 style={{ color: 'var(--dashboard-black, #000000)' }}>5.2 Access Controls</h3>
            <ul>
              <li>Multi-factor authentication for administrative access</li>
              <li>Role-based access controls within our systems</li>
              <li>Regular security audits and penetration testing</li>
              <li>Employee background checks and security training</li>
            </ul>
          </div>

          <div id="data-retention">
            <h3 style={{ color: 'var(--dashboard-black, #000000)' }}>5.3 Data Retention</h3>
            <ul>
              <li><strong>Meeting Data:</strong> Retained until user deletion or account termination</li>
              <li><strong>Account Information:</strong> Retained for active accounts plus 90 days after deactivation</li>
              <li><strong>Analytics Data:</strong> Aggregated data retained for up to 3 years</li>
              <li><strong>Legal Compliance:</strong> Some data may be retained longer if required by law</li>
            </ul>
          </div>
        </section>

        <section id="your-rights">
          <h2 style={{ color: 'var(--dashboard-black, #000000)' }}>6. Your Rights</h2>
          
          <div id="access-portability">
            <h3 style={{ color: 'var(--dashboard-black, #000000)' }}>6.1 Access and Portability</h3>
            <ul>
              <li>Request a copy of your personal data</li>
              <li>Export your meeting transcripts and summaries</li>
              <li>Download your account information</li>
              <li>Receive data in a machine-readable format</li>
            </ul>
          </div>

          <div id="correction-deletion">
            <h3 style={{ color: 'var(--dashboard-black, #000000)' }}>6.2 Correction and Deletion</h3>
            <ul>
              <li>Update or correct your profile information</li>
              <li>Delete specific meetings or transcripts</li>
              <li>Request complete account deletion</li>
              <li>Opt-out of specific data processing activities</li>
            </ul>
          </div>

          <div id="opt-out">
            <h3 style={{ color: 'var(--dashboard-black, #000000)' }}>6.3 Opt-Out Preferences</h3>
            <ul>
              <li>Unsubscribe from marketing communications</li>
              <li>Disable non-essential analytics tracking</li>
              <li>Control third-party integration permissions</li>
              <li>Manage notification preferences</li>
            </ul>
          </div>
        </section>

        <section id="international-users">
          <h2 style={{ color: 'var(--dashboard-black, #000000)' }}>7. International Users</h2>
          
          <div id="kazakhstan-law">
            <h3 style={{ color: 'var(--dashboard-black, #000000)' }}>7.1 Kazakhstan Law Compliance</h3>
            <p>
              As a company based in Kazakhstan, we comply with the Republic of Kazakhstan's data protection laws, 
              including the Law on Personal Data and its Protection. We ensure that:
            </p>
            <ul>
              <li>Personal data processing is lawful and transparent</li>
              <li>Data subjects have rights to access and correct their information</li>
              <li>Appropriate technical and organizational measures protect personal data</li>
              <li>Cross-border data transfers comply with applicable regulations</li>
            </ul>
          </div>

          <div id="gdpr-considerations">
            <h3 style={{ color: 'var(--dashboard-black, #000000)' }}>7.2 GDPR Considerations</h3>
            <p>For users in the European Union, we provide additional protections under GDPR:</p>
            <ul>
              <li>Clear legal basis for all data processing activities</li>
              <li>Enhanced rights including data portability and erasure</li>
              <li>Data Protection Impact Assessments for high-risk processing</li>
              <li>Appointment of a Data Protection Officer when required</li>
            </ul>
          </div>

          <div id="data-transfers">
            <h3 style={{ color: 'var(--dashboard-black, #000000)' }}>7.3 International Data Transfers</h3>
            <p>
              We may transfer data internationally to provide our services. All transfers are protected by:
            </p>
            <ul>
              <li>Standard Contractual Clauses approved by relevant authorities</li>
              <li>Adequacy decisions where available</li>
              <li>Additional safeguards for sensitive data</li>
              <li>Regular review of transfer mechanisms</li>
            </ul>
          </div>
        </section>

        <section id="children-privacy">
          <h2 style={{ color: 'var(--dashboard-black, #000000)' }}>8. Children's Privacy</h2>
          <p>
            Our Service is not intended for use by children under the age of 16. We do not knowingly collect 
            personal information from children under 16. If you become aware that a child has provided us with 
            personal information, please contact us immediately. If we discover that a child under 16 has 
            provided us with personal information, we will delete such information from our servers.
          </p>
        </section>

        <section id="changes-to-policy">
          <h2 style={{ color: 'var(--dashboard-black, #000000)' }}>9. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. We will notify you of any changes by:
          </p>
          <ul>
            <li>Posting the updated policy on our website</li>
            <li>Sending an email notification to registered users</li>
            <li>Displaying a prominent notice on our platform</li>
            <li>Providing at least 30 days notice for material changes</li>
          </ul>
          <p>
            Your continued use of the Service after any modifications indicates your acceptance of the updated Privacy Policy.
          </p>
        </section>

        <section id="contact-us">
          <h2 style={{ color: 'var(--dashboard-black, #000000)' }}>10. Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy or our privacy practices, please contact us at:
          </p>
          <div className="contact-info">
            <p><strong>Raven AI</strong></p>
            <p><strong>CEO:</strong> Arnur Artykbay</p>
            <p><strong>Address:</strong> Almaty, Kazakhstan</p>
            <p><strong>Email:</strong> <a href="mailto:arnurartyqbay@gmail.com" style={{ color: 'var(--dashboard-bright-blue, #83BAFF)' }}>arnurartyqbay@gmail.com</a></p>
            <p><strong>Phone:</strong> <a href="tel:+77083883090" style={{ color: 'var(--dashboard-bright-blue, #83BAFF)' }}>+7 708 388 3090</a></p>
            <p><strong>Website:</strong> <a href="https://ravenai.site" style={{ color: 'var(--dashboard-bright-blue, #83BAFF)' }}>https://ravenai.site</a></p>
          </div>
          <p>
            For data protection inquiries, please include "Privacy Policy" in the subject line of your email. 
            We will respond to your inquiry within 30 days.
          </p>
        </section>
      </div>
    </LegalLayout>
  );
}; 